fix: import `@nuxt/test-utils/runtime` after `vitest` to avoid vitest runner error
I got the following error:

```
...
stderr | tests/nuxt/content-rich.test.ts
[Vue warn]: Unhandled error during execution of watcher callback
<empty line>

 ❯ tests/nuxt/content-rich.test.ts  (0 test)
 ✓ tests/unit/language.test.ts  (1 test) 17ms
 ✓ tests/unit/permalinks.test.ts  (6 tests) 6ms
 ✓ tests/unit/reorder-timeline.test.ts  (2 tests) 7ms

⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/nuxt/content-rich.test.ts [ tests/nuxt/content-rich.test.ts ]
ReferenceError: Cannot access '__vi_import_2__' before initialization
 ❯ Proxy.pausableWatch tests/nuxt/content-rich.test.ts:48:19

 ❯ useStorage node_modules/.pnpm/@vueuse+core@11.0.3_vue@3.5.4_typescript@5.6.2_/node_modules/@vueuse/core/index.mjs:1719:76
 ❯ Module.useLocalStorage node_modules/.pnpm/@vueuse+core@11.0.3_vue@3.5.4_typescript@5.6.2_/node_modules/@vueuse/core/index.mjs:4240:10
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
 ❯ composables/dialog.ts:25:14
 ❯ composables/users.ts:10:[31](https://github.com/elk-zone/elk/runs/30833954418#step:7:32)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Vitest caught 1 unhandled error during the test run.
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
ReferenceError: Cannot access '__vi_import_2__' before initialization
 ❯ Proxy.pausableWatch tests/nuxt/content-rich.test.ts:48:19

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
 ❯ useStorage node_modules/.pnpm/@vueuse+core@11.0.3_vue@3.5.4_typescript@5.6.2_/node_modules/@vueuse/core/index.mjs:1719:76
 ❯ Module.useLocalStorage node_modules/.pnpm/@vueuse+core@11.0.3_vue@3.5.4_typescript@5.6.2_/node_modules/@vueuse/core/index.mjs:4240:10
 ❯ composables/dialog.ts:25:14
 ❯ processTicksAndRejections node:internal/process/task_queues:95:5
 ❯ VitestExecutor.runModule node_modules/.pnpm/vite-node@2.1.1_@types+node@20.8.6_terser@5.22.0/node_modules/vite-node/dist/client.mjs:399:5
 ❯ VitestExecutor.directRequest node_modules/.pnpm/vite-node@2.1.1_@types+node@20.8.6_terser@5.22.0/node_modules/vite-node/dist/client.mjs:381:5
 ❯ VitestExecutor.cachedRequest node_modules/.pnpm/vite-node@2.1.1_@types+node@20.8.6_terser@5.22.0/node_modules/vite-node/dist/client.mjs:206:14
 ❯ VitestExecutor.dependencyRequest node_modules/.pnpm/vite-node@2.1.1_@types+node@20.8.6_terser@5.22.0/node_modules/vite-node/dist/client.mjs:259:12
 ❯ composables/users.ts:10:31

This error originated in "tests/nuxt/content-rich.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "tests/nuxt/content-rich.test.ts". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.

 Test Files  1 failed | 5 passed (6)
      Tests  20 passed (20)
     Errors  1 error
   Start at  04:46:[33](https://github.com/elk-zone/elk/runs/30833954418#step:7:34)
   Duration  5.48s (transform 4.31s, setup 9.08s, collect 1.95s, tests 159ms, environment 1.11s, prepare 1.18s)
...
```